// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_SRAM       = 32'h 00100000;
  localparam logic [31:0] ADDR_SPACE_UART       = 32'h 80000000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER   = 32'h 40500000;
  localparam logic [31:0] ADDR_SPACE_RV_PLIC    = 32'h 48000000;
  localparam logic [31:0] ADDR_SPACE_SPI_HOST   = 32'h 40300000;
  localparam logic [31:0] ADDR_SPACE_RV_DM_MEM  = 32'h 00010000;
  localparam logic [31:0] ADDR_SPACE_RV_DM_REGS = 32'h 40400000;

  localparam logic [31:0] ADDR_MASK_SRAM       = 32'h 0001ffff;
  localparam logic [31:0] ADDR_MASK_UART       = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER   = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_RV_PLIC    = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_SPI_HOST   = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_DM_MEM  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_DM_REGS = 32'h 00000fff;

  localparam int N_HOST   = 3;
  localparam int N_DEVICE = 7;

  typedef enum int {
    TlSram = 0,
    TlUart = 1,
    TlRvTimer = 2,
    TlRvPlic = 3,
    TlSpiHost = 4,
    TlRvDmMem = 5,
    TlRvDmRegs = 6
  } tl_device_e;

  typedef enum int {
    TlIbexLsu = 0,
    TlRvDmSba = 1,
    TlIbexInstr = 2
  } tl_host_e;

endpackage
