// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// ibex_lsu
//   -> s1n_10
//     -> sm1_11
//       -> sram
//     -> sm1_12
//       -> uart
//     -> sm1_13
//       -> rv_dm_mem
//     -> rv_dm_regs
//     -> sm1_14
//       -> spi_host
//     -> sm1_15
//       -> rv_timer
//     -> sm1_16
//       -> rv_plic
// rv_dm_sba
//   -> s1n_17
//     -> sm1_11
//       -> sram
//     -> sm1_12
//       -> uart
//     -> sm1_14
//       -> spi_host
//     -> sm1_15
//       -> rv_timer
//     -> sm1_16
//       -> rv_plic
// ibex_instr
//   -> s1n_18
//     -> sm1_11
//       -> sram
//     -> sm1_13
//       -> rv_dm_mem

module xbar_main (
  input clk_i,
  input rst_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_ibex_lsu_i,
  output tlul_pkg::tl_d2h_t tl_ibex_lsu_o,
  input  tlul_pkg::tl_h2d_t tl_rv_dm_sba_i,
  output tlul_pkg::tl_d2h_t tl_rv_dm_sba_o,
  input  tlul_pkg::tl_h2d_t tl_ibex_instr_i,
  output tlul_pkg::tl_d2h_t tl_ibex_instr_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_sram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_i,
  output tlul_pkg::tl_h2d_t tl_uart_o,
  input  tlul_pkg::tl_d2h_t tl_uart_i,
  output tlul_pkg::tl_h2d_t tl_rv_timer_o,
  input  tlul_pkg::tl_d2h_t tl_rv_timer_i,
  output tlul_pkg::tl_h2d_t tl_rv_plic_o,
  input  tlul_pkg::tl_d2h_t tl_rv_plic_i,
  output tlul_pkg::tl_h2d_t tl_spi_host_o,
  input  tlul_pkg::tl_d2h_t tl_spi_host_i,
  output tlul_pkg::tl_h2d_t tl_rv_dm_mem_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm_mem_i,
  output tlul_pkg::tl_h2d_t tl_rv_dm_regs_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm_regs_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_main_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_10_us_h2d ;
  tl_d2h_t tl_s1n_10_us_d2h ;


  tl_h2d_t tl_s1n_10_ds_h2d [7];
  tl_d2h_t tl_s1n_10_ds_d2h [7];

  // Create steering signal
  logic [2:0] dev_sel_s1n_10;


  tl_h2d_t tl_sm1_11_us_h2d [3];
  tl_d2h_t tl_sm1_11_us_d2h [3];

  tl_h2d_t tl_sm1_11_ds_h2d ;
  tl_d2h_t tl_sm1_11_ds_d2h ;


  tl_h2d_t tl_sm1_12_us_h2d [2];
  tl_d2h_t tl_sm1_12_us_d2h [2];

  tl_h2d_t tl_sm1_12_ds_h2d ;
  tl_d2h_t tl_sm1_12_ds_d2h ;


  tl_h2d_t tl_sm1_13_us_h2d [2];
  tl_d2h_t tl_sm1_13_us_d2h [2];

  tl_h2d_t tl_sm1_13_ds_h2d ;
  tl_d2h_t tl_sm1_13_ds_d2h ;


  tl_h2d_t tl_sm1_14_us_h2d [2];
  tl_d2h_t tl_sm1_14_us_d2h [2];

  tl_h2d_t tl_sm1_14_ds_h2d ;
  tl_d2h_t tl_sm1_14_ds_d2h ;


  tl_h2d_t tl_sm1_15_us_h2d [2];
  tl_d2h_t tl_sm1_15_us_d2h [2];

  tl_h2d_t tl_sm1_15_ds_h2d ;
  tl_d2h_t tl_sm1_15_ds_d2h ;


  tl_h2d_t tl_sm1_16_us_h2d [2];
  tl_d2h_t tl_sm1_16_us_d2h [2];

  tl_h2d_t tl_sm1_16_ds_h2d ;
  tl_d2h_t tl_sm1_16_ds_d2h ;

  tl_h2d_t tl_s1n_17_us_h2d ;
  tl_d2h_t tl_s1n_17_us_d2h ;


  tl_h2d_t tl_s1n_17_ds_h2d [5];
  tl_d2h_t tl_s1n_17_ds_d2h [5];

  // Create steering signal
  logic [2:0] dev_sel_s1n_17;

  tl_h2d_t tl_s1n_18_us_h2d ;
  tl_d2h_t tl_s1n_18_us_d2h ;


  tl_h2d_t tl_s1n_18_ds_h2d [2];
  tl_d2h_t tl_s1n_18_ds_d2h [2];

  // Create steering signal
  logic [1:0] dev_sel_s1n_18;



  assign tl_sm1_11_us_h2d[0] = tl_s1n_10_ds_h2d[0];
  assign tl_s1n_10_ds_d2h[0] = tl_sm1_11_us_d2h[0];

  assign tl_sm1_12_us_h2d[0] = tl_s1n_10_ds_h2d[1];
  assign tl_s1n_10_ds_d2h[1] = tl_sm1_12_us_d2h[0];

  assign tl_sm1_13_us_h2d[0] = tl_s1n_10_ds_h2d[2];
  assign tl_s1n_10_ds_d2h[2] = tl_sm1_13_us_d2h[0];

  assign tl_rv_dm_regs_o = tl_s1n_10_ds_h2d[3];
  assign tl_s1n_10_ds_d2h[3] = tl_rv_dm_regs_i;

  assign tl_sm1_14_us_h2d[0] = tl_s1n_10_ds_h2d[4];
  assign tl_s1n_10_ds_d2h[4] = tl_sm1_14_us_d2h[0];

  assign tl_sm1_15_us_h2d[0] = tl_s1n_10_ds_h2d[5];
  assign tl_s1n_10_ds_d2h[5] = tl_sm1_15_us_d2h[0];

  assign tl_sm1_16_us_h2d[0] = tl_s1n_10_ds_h2d[6];
  assign tl_s1n_10_ds_d2h[6] = tl_sm1_16_us_d2h[0];

  assign tl_sm1_11_us_h2d[1] = tl_s1n_18_ds_h2d[0];
  assign tl_s1n_18_ds_d2h[0] = tl_sm1_11_us_d2h[1];

  assign tl_sm1_13_us_h2d[1] = tl_s1n_18_ds_h2d[1];
  assign tl_s1n_18_ds_d2h[1] = tl_sm1_13_us_d2h[1];

  assign tl_sm1_11_us_h2d[2] = tl_s1n_17_ds_h2d[0];
  assign tl_s1n_17_ds_d2h[0] = tl_sm1_11_us_d2h[2];

  assign tl_sm1_12_us_h2d[1] = tl_s1n_17_ds_h2d[1];
  assign tl_s1n_17_ds_d2h[1] = tl_sm1_12_us_d2h[1];

  assign tl_sm1_14_us_h2d[1] = tl_s1n_17_ds_h2d[2];
  assign tl_s1n_17_ds_d2h[2] = tl_sm1_14_us_d2h[1];

  assign tl_sm1_15_us_h2d[1] = tl_s1n_17_ds_h2d[3];
  assign tl_s1n_17_ds_d2h[3] = tl_sm1_15_us_d2h[1];

  assign tl_sm1_16_us_h2d[1] = tl_s1n_17_ds_h2d[4];
  assign tl_s1n_17_ds_d2h[4] = tl_sm1_16_us_d2h[1];

  assign tl_s1n_10_us_h2d = tl_ibex_lsu_i;
  assign tl_ibex_lsu_o = tl_s1n_10_us_d2h;

  assign tl_sram_o = tl_sm1_11_ds_h2d;
  assign tl_sm1_11_ds_d2h = tl_sram_i;

  assign tl_uart_o = tl_sm1_12_ds_h2d;
  assign tl_sm1_12_ds_d2h = tl_uart_i;

  assign tl_rv_dm_mem_o = tl_sm1_13_ds_h2d;
  assign tl_sm1_13_ds_d2h = tl_rv_dm_mem_i;

  assign tl_spi_host_o = tl_sm1_14_ds_h2d;
  assign tl_sm1_14_ds_d2h = tl_spi_host_i;

  assign tl_rv_timer_o = tl_sm1_15_ds_h2d;
  assign tl_sm1_15_ds_d2h = tl_rv_timer_i;

  assign tl_rv_plic_o = tl_sm1_16_ds_h2d;
  assign tl_sm1_16_ds_d2h = tl_rv_plic_i;

  assign tl_s1n_17_us_h2d = tl_rv_dm_sba_i;
  assign tl_rv_dm_sba_o = tl_s1n_17_us_d2h;

  assign tl_s1n_18_us_h2d = tl_ibex_instr_i;
  assign tl_ibex_instr_o = tl_s1n_18_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_10 = 3'd7;
    if ((tl_s1n_10_us_h2d.a_address &
         ~(ADDR_MASK_SRAM)) == ADDR_SPACE_SRAM) begin
      dev_sel_s1n_10 = 3'd0;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_UART)) == ADDR_SPACE_UART) begin
      dev_sel_s1n_10 = 3'd1;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM_MEM)) == ADDR_SPACE_RV_DM_MEM) begin
      dev_sel_s1n_10 = 3'd2;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM_REGS)) == ADDR_SPACE_RV_DM_REGS) begin
      dev_sel_s1n_10 = 3'd3;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_SPI_HOST)) == ADDR_SPACE_SPI_HOST) begin
      dev_sel_s1n_10 = 3'd4;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_RV_TIMER)) == ADDR_SPACE_RV_TIMER) begin
      dev_sel_s1n_10 = 3'd5;

    end else if ((tl_s1n_10_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC)) == ADDR_SPACE_RV_PLIC) begin
      dev_sel_s1n_10 = 3'd6;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_17 = 3'd5;
    if ((tl_s1n_17_us_h2d.a_address &
         ~(ADDR_MASK_SRAM)) == ADDR_SPACE_SRAM) begin
      dev_sel_s1n_17 = 3'd0;

    end else if ((tl_s1n_17_us_h2d.a_address &
                  ~(ADDR_MASK_UART)) == ADDR_SPACE_UART) begin
      dev_sel_s1n_17 = 3'd1;

    end else if ((tl_s1n_17_us_h2d.a_address &
                  ~(ADDR_MASK_SPI_HOST)) == ADDR_SPACE_SPI_HOST) begin
      dev_sel_s1n_17 = 3'd2;

    end else if ((tl_s1n_17_us_h2d.a_address &
                  ~(ADDR_MASK_RV_TIMER)) == ADDR_SPACE_RV_TIMER) begin
      dev_sel_s1n_17 = 3'd3;

    end else if ((tl_s1n_17_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC)) == ADDR_SPACE_RV_PLIC) begin
      dev_sel_s1n_17 = 3'd4;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_18 = 2'd2;
    if ((tl_s1n_18_us_h2d.a_address &
         ~(ADDR_MASK_SRAM)) == ADDR_SPACE_SRAM) begin
      dev_sel_s1n_18 = 2'd0;

    end else if ((tl_s1n_18_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM_MEM)) == ADDR_SPACE_RV_DM_MEM) begin
      dev_sel_s1n_18 = 2'd1;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (28'h0),
    .DRspDepth (28'h0),
    .N         (7)
  ) u_s1n_10 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_10_us_h2d),
    .tl_h_o       (tl_s1n_10_us_d2h),
    .tl_d_o       (tl_s1n_10_ds_h2d),
    .tl_d_i       (tl_s1n_10_ds_d2h),
    .dev_select_i (dev_sel_s1n_10)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (3)
  ) u_sm1_11 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_11_us_h2d),
    .tl_h_o       (tl_sm1_11_us_d2h),
    .tl_d_o       (tl_sm1_11_ds_h2d),
    .tl_d_i       (tl_sm1_11_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_12 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_12_us_h2d),
    .tl_h_o       (tl_sm1_12_us_d2h),
    .tl_d_o       (tl_sm1_12_ds_h2d),
    .tl_d_i       (tl_sm1_12_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_13 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_13_us_h2d),
    .tl_h_o       (tl_sm1_13_us_d2h),
    .tl_d_o       (tl_sm1_13_ds_h2d),
    .tl_d_i       (tl_sm1_13_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_14 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_14_us_h2d),
    .tl_h_o       (tl_sm1_14_us_d2h),
    .tl_d_o       (tl_sm1_14_ds_h2d),
    .tl_d_i       (tl_sm1_14_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_15 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_15_us_h2d),
    .tl_h_o       (tl_sm1_15_us_d2h),
    .tl_d_o       (tl_sm1_15_ds_h2d),
    .tl_d_i       (tl_sm1_15_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_16 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_16_us_h2d),
    .tl_h_o       (tl_sm1_16_us_d2h),
    .tl_d_o       (tl_sm1_16_ds_h2d),
    .tl_d_i       (tl_sm1_16_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (20'h0),
    .DRspDepth (20'h0),
    .N         (5)
  ) u_s1n_17 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_17_us_h2d),
    .tl_h_o       (tl_s1n_17_us_d2h),
    .tl_d_o       (tl_s1n_17_ds_h2d),
    .tl_d_i       (tl_s1n_17_ds_d2h),
    .dev_select_i (dev_sel_s1n_17)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (8'h0),
    .DRspDepth (8'h0),
    .N         (2)
  ) u_s1n_18 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_18_us_h2d),
    .tl_h_o       (tl_s1n_18_us_d2h),
    .tl_d_o       (tl_s1n_18_ds_h2d),
    .tl_d_i       (tl_s1n_18_ds_d2h),
    .dev_select_i (dev_sel_s1n_18)
  );

endmodule
